---
name: "Build"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
        id: go

      - name: Build
        run: make

      - name: Test
        run: make container

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: jamesread
          password: ${{ secrets.CONTAINER_TOKEN }}

      - name: Push to ghcr
        run: docker push ghcr.io/jamesread/uncomplicated-alert-receiver:latest
